(()=>{
 const form=document.querySelector('#intakeForm'),kind=document.querySelector('#intakeKind'),record=document.querySelector('#intakeRecord'),result=document.querySelector('#intakeResult'),output=document.querySelector('#intakeOutput'),status=document.querySelector('#intakeStatus');
 const rows=window.STAR_MAP_RESOURCES||[];let generated='';
 rows.forEach(r=>{const o=document.createElement('option');o.value=r.id;o.textContent=(r.representativeProject||r.name)+' · '+r.name;record.append(o);});
 function mode(){record.required=kind.value==='correction';record.disabled=kind.value!=='correction';record.options[0].textContent=record.required?'请选择需要更新的档案':'新项目无需选择';}
 function fill(){const r=rows.find(r=>r.id===record.value);if(r){form.elements.team.value=r.name;form.elements.project.value=r.representativeProject||'';}}
 kind.addEventListener('change',mode);record.addEventListener('change',fill);
 const initial=new URLSearchParams(location.search).get('project');if(rows.some(r=>r.id===initial)){kind.value='correction';record.value=initial;fill();}mode();
 form.addEventListener('input',e=>{e.target.setCustomValidity?.('');generated='';result.hidden=true;status.textContent='';});form.addEventListener('change',()=>{generated='';result.hidden=true;});
 form.addEventListener('submit',e=>{e.preventDefault();for(const name of ['team','project','description']){const input=form.elements[name];input.setCustomValidity(input.value.trim()?'':'请填写有效内容，不能只有空格。');if(!input.checkValidity()){input.reportValidity();return;}}const f=new FormData(form);const links=String(f.get('links')||'').split(/\r?\n/).map(s=>s.trim()).filter(Boolean);const field=form.elements.links;field.setCustomValidity('');for(const link of links){try{const u=new URL(link);if(!['https:','http:'].includes(u.protocol)||u.username||u.password)throw Error();}catch{field.setCustomValidity('链接须以 http:// 或 https:// 开头，且不能包含账号密码。');field.reportValidity();return;}}
  generated=['星游集 · 待运营核对资料','类型：'+(kind.value==='correction'?'更新 / 纠错':'新项目'),'档案 ID：'+(record.disabled?'未分配':record.value),'团队：'+String(f.get('team')).trim(),'作品：'+String(f.get('project')).trim(),'内容：\n'+String(f.get('description')).trim(),'阶段：'+(f.get('stage')||'未填写'),'平台：'+(f.get('platform')||'未填写'),'链接：\n'+(links.join('\n')||'未填写'),'支持需求 / 补充：\n'+(f.get('needs')||'未填写'),'展示意愿：'+(f.get('permission')==='public'?'同意公开本次提交的作品资料':'仅供运营核对，暂不公开'),'填写人已确认有权提交资料。','状态：仅生成，未发送、未发布'].join('\n\n');output.value=generated;result.hidden=false;status.textContent='请检查资料，再复制或下载并发给运营。';document.querySelector('#resultTitle').focus();result.scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});
 });
 form.elements.links.addEventListener('input',()=>form.elements.links.setCustomValidity(''));
 document.querySelector('#copyIntake').addEventListener('click',async()=>{if(!generated)return;try{await navigator.clipboard.writeText(generated);status.textContent='已复制；请粘贴到与运营的微信对话中发送。';}catch{output.focus();output.select();status.textContent='自动复制不可用，已选中文本，请手动复制。';}});
 document.querySelector('#downloadIntake').addEventListener('click',()=>{if(!generated)return;const url=URL.createObjectURL(new Blob(['\ufeff'+generated],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='星游集-待发送资料.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status.textContent='已发起文件下载；请将文件交给运营，尚未自动发送。';});
})();
